spring.application.name=${APP_NAME:universal-auth-api}
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${APP_PROFILE:mysql}
server.port=${SERVER_PORT:7000}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.flyway.enabled=${FLYWAY_ENABLED:false}
spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:false}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Security Configuration
security.public-paths=${SECURITY_PUBLIC_PATHS:/api/auth/register,/api/auth/login,/api/auth/forgot-password,/api/auth/reset-password}
security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}

# Auth Configuration
auth.registration.default-role=${AUTH_DEFAULT_ROLE:STUDENT}
auth.registration.allowed-roles=${AUTH_ALLOWED_ROLES:TUTOR,STUDENT,PARENT,ADMIN}

# Email Configuration (SMTP Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
